site_name: IQRFBB-10
docs_dir: documents
site_dir: docs/book
site_url: http://logimic.com/iqrfboard/book/
site_author: Logimic
copyright: Copyright 2018, All rights reserved, Logimic, s.r.o.

nav:
- GettingStarted: README.md
- IQRF Network:
  - Setup IQRF Network: SetupIqrfNetwork.md
  - IQRF Gateway Daemon: IqrfGatewayDaemon.md
- Examples: examples/README.md
- About: About.md
