site_name: IQRFBB-10
docs_dir: documents
site_dir: docs/book

nav:
    - GettingStarted: ./
    - Setup IQRF Network: SetupIqrfNetwork.md
    - IQRF Gateway Daemon: IqrfGatewayDaemon.md
    - Examples: examples/README.md