/**
* Copyright Logimic,s.r.o., www.logimic.com
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

// Online DPA documentation http://www.iqrf.org/DpaTechGuide/

// This example implements the user peripheral reading from HUD21D
// PNUM = 0x20 and PCMD = 0 returns 3 bytes with result read from MCP9802
// Based on example CustomDpaHandler-UserPeripheral-i2c.c by IQRF Tech s.r.o.

// Default IQRF include (modify the path according to your setup)
#include "include/IQRF_OS/IQRF.h"

// Default DPA header (modify the path according to your setup)
#include "include/DPA/DPA.h"
// Default Custom DPA Handler header (modify the path according to your setup)
#include "include/DPA/DPAcustomHandler.h"
// IQRF standards header (modify the path according to your setup)
#include "include/DPA/IQRFstandard.h"
#include "include/DPA/IQRF_HWPID.h"

//############################################################################################

void i2c_init();
void i2c_shutdown();
void i2c_waitForIdle();
void i2c_start();
void i2c_repStart();
void i2c_stop();
uns8 i2c_read( bit ack );
void i2c_write( uns8 i2cWriteData );

//#define I2C_ADR         	0b10010110
#define PWR_SENSOR_TRIS 	TRISC.7
#define PWR_SENSOR_IO   	LATC.7

#define   HTU21D_I2C_ADDR 0x80 // 0x40 << 1 => 7bit addrres
#define   HTU21D_TEMP     0xF3
#define   HTU21D_HUMID    0xF5

// Must be the 1st defined function in the source code in order to be placed at the correct FLASH location!
//############################################################################################
bit CustomDpaHandler()
//############################################################################################
{
  // Handler presence mark
  clrwdt();

  // Detect DPA event to handle
  switch ( GetDpaEvent() )
  {
    // -------------------------------------------------
    case DpaEvent_Interrupt:
      // Do an extra quick background interrupt work
      // ! The time spent handling this event is critical.If there is no interrupt to handle return immediately otherwise keep the code as fast as possible.
      // ! Make sure the event is the 1st case in the main switch statement at the handler routine.This ensures that the event is handled as the 1st one.
      // ! It is desirable that this event is handled with immediate return even if it is not used by the custom handler because the Interrupt event is raised on every MCU interrupt and the �empty� return handler ensures the shortest possible interrupt routine response time.
      // ! Only global variables or local ones marked by static keyword can be used to allow reentrancy.
      // ! Make sure race condition does not occur when accessing those variables at other places.
      // ! Make sure( inspect.lst file generated by C compiler ) compiler does not create any hidden temporary local variable( occurs when using division, multiplication or bit shifts ) at the event handler code.The name of such variable is usually Cnumbercnt.
      // ! Do not call any OS functions except setINDFx().
      // ! Do not use any OS variables especially for writing access.
      // ! All above rules apply also to any other function being called from the event handler code, although calling any function from Interrupt event is not recommended because of additional MCU stack usage.

DpaHandleReturnTRUE:
      return TRUE;

      // -------------------------------------------------
    case DpaEvent_Init:
      // Do a one time initialization work before main loop starts
    case DpaEvent_AfterSleep:
      // Called after woken up after sleep

      i2c_init();
      break;

      // -------------------------------------------------
    case DpaEvent_BeforeSleep:
      // Called before going to sleep

      i2c_shutdown();
      break;

      // -------------------------------------------------
    case DpaEvent_DpaRequest:
      // Called to interpret DPA request for peripherals
      // -------------------------------------------------
      // Peripheral enumeration
      if ( IsDpaEnumPeripheralsRequest() )
      {
        // We implement 1 user peripheral
        _DpaMessage.EnumPeripheralsAnswer.UserPerNr = 1;
        FlagUserPer( _DpaMessage.EnumPeripheralsAnswer.UserPer, PNUM_USER + 0 );
        _DpaMessage.EnumPeripheralsAnswer.HWPID = 0x000F;
        _DpaMessage.EnumPeripheralsAnswer.HWPIDver = 0xAbCd;

        goto DpaHandleReturnTRUE;
      }
      // -------------------------------------------------
      // Get information about peripheral
      else if ( IsDpaPeripheralInfoRequest() )
      {
        if ( _PNUM == PNUM_USER + 0 )
        {
          _DpaMessage.PeripheralInfoAnswer.PerT = PERIPHERAL_TYPE_USER_AREA;
          _DpaMessage.PeripheralInfoAnswer.PerTE = PERIPHERAL_TYPE_EXTENDED_READ;
          goto DpaHandleReturnTRUE;
        }

        break;
      }
      // -------------------------------------------------
      else
      {
        // Handle peripheral command
        if ( _PNUM == PNUM_USER + 0 )
        {
          // Check command
          switch ( _PCMD )
          {
            case 0:
              // -------------------------------------------------
              // Read temperature
              if (_DpaDataLength != 0)
                DpaApiReturnPeripheralError(ERROR_DATA_LEN);

              // temperature
              i2c_start();
              i2c_write(HTU21D_I2C_ADDR);       // HTU21D address
              i2c_write(HTU21D_TEMP);           // get temperature cmd hold master
              i2c_stop();

              waitMS(50);                       // wait for measurement

              i2c_start();
              i2c_write(HTU21D_I2C_ADDR | 1);   // HTU21D address + read
              _DpaMessage.Response.PData[0] = i2c_read(TRUE);         // MSB
              _DpaMessage.Response.PData[1] = i2c_read(TRUE);         // LSB
              _DpaMessage.Response.PData[2] = i2c_read(FALSE);        // checksum - may be ommited by NACK previous byte
              i2c_stop();

              // thumidityemperature
              i2c_start();
              i2c_write(HTU21D_I2C_ADDR);       // HTU21D address
              i2c_write(HTU21D_HUMID);          // get humidity cmd hold master
              i2c_stop();

              waitMS(50);                       // wait for measurement

              i2c_start();
              i2c_write(HTU21D_I2C_ADDR | 1);   // HTU21D address + read
              _DpaMessage.Response.PData[3] = i2c_read(TRUE);         // MSB
              _DpaMessage.Response.PData[4] = i2c_read(TRUE);         // LSB
              _DpaMessage.Response.PData[5] = i2c_read(FALSE);        // checksum - may be ommited by NACK previous byte 
              i2c_stop();

              _DpaDataLength = 6;
              goto DpaHandleReturnTRUE;

            default:
              // -------------------------------------------------
              // Invalid command
              DpaApiReturnPeripheralError( ERROR_PCMD );
          }
        }
      }
  }

  return FALSE;
}

//############################################################################################

#pragma library 1	// Compile only used functions

// *********************************************************************

void writeToSSPCON2( uns8 value @ param4.high8 )
{
  writeToRAM( &SSPCON2, value );
}
//----------------------------------------------------------------------

void writeOredToSSPCON2( uns8 value @ param4.high8 )
{
  writeToSSPCON2( SSPCON2 | value );
}

//----------------------------------------------------------------------

void i2c_init()
{
  PORTC = 0x80;                       // port

  TRISC.3 = 1;                        // SCL as input (SIM C6)
  TRISC.4 = 1;                        // SDA as input (SIM C7)

  PWR_SENSOR_TRIS = 0;                // sensor power as output (SIM C8)
  TRISC.5 = 1;                        // shared with SIM C8

  TRISA.5 = 1;                        // sensor ALERT as input (SIM C5)
  TRISB.4 = 1;                        // shared with SIM C5
  TRISC.6 = 1;                        // shared with SIM C5

  writeToRAM( &SSPCON1, 0x38 );		  // I2C master mode     SSPCON = 0b00111000
  writeToSSPCON2( 0x00 );

  SSPADD = ( F_OSC / 50000 / 4 ) - 2; // 50 kHz SCL frequency

  SMP = 1;                            // Disable slew rate control
}

//------------------------------------------------------------------------

void i2c_shutdown()
{
  writeToRAM( &SSPCON1, 0x00 );		  // I2C master mode     SSPCON = 0
}

//------------------------------------------------------------------------
void i2c_waitForIdle()
{
  while ( SSPCON2 & 0x1F );           // Wait for idle and not writing
  while ( RW_ );                      // Wait for idle and not writing
}
//----------------------------------------------------------------------

void i2c_start()
{
  i2c_waitForIdle();
  writeOredToSSPCON2( 0x01 );		// SEN = 1
}
//----------------------------------------------------------------------

void i2c_repStart()
{
  i2c_waitForIdle();
  writeOredToSSPCON2( 0x02 );		// RSEN = 1
}
//----------------------------------------------------------------------

void i2c_stop()
{
  i2c_waitForIdle();
  writeOredToSSPCON2( 0x04 );		// PEN = 1
}
//----------------------------------------------------------------------

uns8 i2c_read( bit ack )
{
  i2c_waitForIdle();
  writeOredToSSPCON2( 0x08 );		// RCEN = 1

  i2c_waitForIdle();

  uns8 i2cReadData @ userReg0;
  i2cReadData = SSPBUF;

  i2c_waitForIdle();

  if ( ack )
    writeToSSPCON2( SSPCON2 & 0xDF ); // Acknowledge, ACKDT = 0
  else
    writeOredToSSPCON2( 0x20 );		  // Not acknowledge, ACKDT = 1 

  writeOredToSSPCON2( 0x10 );		  // Send acknowledge sequence, ACKEN = 1 
  return i2cReadData;
}
//----------------------------------------------------------------------

void i2c_write( uns8 i2cWriteData @ param2 )
{
  i2c_waitForIdle();
  SSPBUF = i2cWriteData;
}

// ############################################################################################
#pragma library 0	// Compile all
//############################################################################################
// Default Custom DPA Handler header; 2nd include to implement Code bumper to detect too long code of the Custom DPA Handler (modify the path according to your setup) 
#include "include/DPA/DPAcustomHandler.h"
//############################################################################################
